//http://www.listdiff.com/compare-2-lists-difference-tool
["Alain Johanne",
"Apocalyptica",
"Bala",
"Blackbriar",
"Brutus",
"Capra",
"Charlotte Wessels",
"Dogma",
"Doro",
"Eleine",
"Folterkammer",
"Furies",
"Girlschool",
"HANABIE.",
"Heriot",
"Inglorious",
"Isyana Sarasvati",
"Lilith Czar",
"Lutharo",
"Metalite",
"Mimi Barks",
"Motive Black",
"Myrkur",
"New Years Day",
"Predatory Void",
"Saint Agnes",
"Skarlett Riot",
"Sophie Lloyd",
"Svalbard",
"Tarja Turunen",
"The Pretty Reckless",
"Voice of Baceprot",
"Wolvennest",
"chelsea wolfe",
"WICKED ASYLUM",
"Shewolf",
"CASSIDY PARIS",
"ACCIDENTAL PRESIDENT",
"SANGHAM",
"PROJECT RENEGADE",
"MNEMOS",
"VALAR MORGHULIS",
"FAYE WEBSTER",
"CONSPIRACY OF BLACKNESS",
"NEVER OBEY AGAIN",
"PANZERCHRIST",
"NOVA DOLL",
"EXILED HOPE",
"SINHERESY",
"THE FIXER",
"HOLY SHIRE",
"venus 5",
"CHRYSARMONIA",
"ILLUMISHADE",
"HER ALONE"]