## This rule redirects to an external API, signing requests with a secret

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"  

[[redirects]]
  from = "/deezerapi/*"
  to = "https://api.deezer.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

## rule to redirect react pages to base app
[[redirects]]
  from = "/pages/*"
  to = "/index.html "
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

## this rule redirects to ngrok free url to access localhost on mobile
##[[redirects]]
##  from = "/api/*"
##  to = "https://ram-firm-osprey.ngrok-free.app/:splat"
##  status = 200
##  force = true # COMMENT: ensure that we always redirect
##  headers = {X-From = "Netlify"}

##signed = "API_SIGNATURE_TOKEN"