## This rule redirects to an external API, signing requests with a secret

[[redirects]]
  from = "/deezerapi/*"
  to = "https://api.deezer.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

## this rule redirects to ngrok free url to access localhost on mobile
[[redirects]]
  from = "/api/*"
  to = "https://ram-firm-osprey.ngrok-free.app/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

##signed = "API_SIGNATURE_TOKEN"